In [55]:
#1. Import the numpy package under the name np

import numpy as np

In [30]:
# 2. Print the numpy version and the configuration

print(np.__version__)
print(np.show_config())

1.21.5
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSSE3,SSE41,POPCNT,SSE42,AVX,F16C,FMA3,AVX2
    not found = AVX512F,AVX512C

In [31]:
# 3. Create a null vector of size 10

print(np.zeros(10))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [32]:
# How to find the memory size of any array

a=np.zeros((10,10))
print(a)
print(a.size*a.itemsize)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
800


In [39]:
# 5. How to get the documentation of the numpy add function from the command line?
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

In [34]:
# 6. Create a null vector of size 10 but the fifth value which is 1

a=np.zeros(10)
a[4]=1
print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [35]:
# 7. Create a vector with values ranging from 10 to 49
a=np.arange(10,50)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [36]:
# 8. Reverse a vector (first element becomes last)

r=np.flip(a)
print(r)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [37]:
# 9. Create a 3x3 matrix with values ranging from 0 to 8

a=np.arange(0,9).reshape(3,3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [45]:
# 10. Find indices of non-zero elements from [1,2,0,0,4,0]

a=np.nonzero([1,2,0,0,4,0])
print(a)

(array([0, 1, 4], dtype=int64),)


In [47]:
# 11. Create a 3x3 identity matrix 
a=np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [50]:
#12. Create a 3x3x3 array with random values

a=np.random.random((3,3,3))
print(a)

[[[0.01821248 0.80117772 0.23582517]
  [0.66450678 0.68150499 0.26878218]
  [0.87007874 0.60742479 0.76174254]]

 [[0.2591743  0.94624657 0.10076625]
  [0.57806179 0.56866155 0.38128948]
  [0.03682116 0.35391182 0.40931242]]

 [[0.11248632 0.45110187 0.84951569]
  [0.23138298 0.21062988 0.11363822]
  [0.39905832 0.81188487 0.37317544]]]


In [54]:
# 13. Create a 10x10 array with random values and find the minimum and maximum values 

a=np.random.random((10,10))
amin, amax = a.min(), a.max()
print(amin, amax )

0.00017102731283413775 0.9977293382476773


In [59]:
# 14. Create a random vector of size 30 and find the mean value 

a=np.random.random((30))

print(a.mean())

0.5608311339738733


In [60]:
#15. Create a 2d array with 1 on the border and 0 inside

a = np.ones((10,10))
a[1:-1,1:-1] = 0
print(a)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [64]:
# 16. How to add a border (filled with 0's) around an existing array?

a = np.ones((10,10))
a[:, [0, -1]] = 0
a[[0, -1], :] = 0
print(a)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [65]:
# 17. What is the result of the following expression?

print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


In [66]:
# 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

a= np.diag(1+np.arange(4),k=-1)
print(a)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [67]:
# 19. Create a 8x8 matrix and fill it with a checkerboard pattern

a = np.zeros((8,8),dtype=int)
a[1::2,::2] = 1
a[::2,1::2] = 1
print(a)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [70]:
# 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 

a=np.unravel_index(99,(6,7,8))
print(a)

(1, 5, 3)


In [71]:
# 21. Create a checkerboard 8x8 matrix using the tile function

a= np.tile( np.array([[0,1],[1,0]]), (4,4))
print(a)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [72]:
# 22. Normalize a 5x5 random matrix

a= np.random.random((5,5))
a= (a- np.mean (a)) / (np.std (a))
print(a)

[[ 0.43004392 -1.1205378  -1.55816483  1.69968946  0.41703867]
 [-1.54570578 -0.39406587  1.11718762  0.3712449   1.48289646]
 [ 1.30062568  0.76461908 -1.26591646 -0.53136871 -0.29599134]
 [-1.11345261  1.00142146  1.59668915 -1.19401894 -0.85520102]
 [-0.06376683 -0.45685236  0.38878914  0.33793122 -0.51313422]]


In [73]:
# 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA)

color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])
print(color)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


In [75]:
# 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)

a= np.dot(np.ones((5,3)), np.ones((3,2)))
print(a)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [76]:
# 25. Given a 1D array, negate all elements which are between 3 and 8, in place.

a = np.arange(11)
a[(3 < a) & (a< 8)] *= -1
print(a)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


In [77]:
# 26. What is the output of the following script?

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


In [79]:
#  27. Consider an integer vector Z, which of these expressions are legal?

print(Z**Z)
print(2 << Z >> 2)
print(Z <- Z)
print(1j*Z)
print(Z/1/1)
print(Z<Z>Z)

[[27. 27.]
 [27. 27.]
 [27. 27.]
 [27. 27.]
 [27. 27.]]


TypeError: ufunc 'left_shift' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

In [81]:
# 28. What are the result of the following expressions?

print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


<ipython-input-81-0cbeeb3dd710>:3: RuntimeWarning: invalid value encountered in true_divide
  print(np.array(0) / np.array(0))
<ipython-input-81-0cbeeb3dd710>:4: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))


In [82]:
# 29. How to round away from zero a float array ?

print(np.where(Z>0, np.ceil(Z), np.floor(Z)))

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [83]:
# 30. How to find common values between two arrays?

Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))

[0 1 2 7 8]


In [85]:
# 31. How to ignore all numpy warnings (not recommended)? 
 

In [86]:
# 32. Is the following expressions true?

print(np.sqrt(-1) == np.emath.sqrt(-1))

False


In [88]:
# 33. How to get the dates of yesterday, today and tomorrow? 

yesterday = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)
print(yesterday,today,tomorrow)

2022-10-12 2022-10-13 2022-10-14


In [89]:
# 34. How to get all the dates corresponding to the month of July 2016?

a= np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(a)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [90]:
# 35. How to compute ((A+B)*(-A/2)) in place (without copy)?

A = np.ones(3)*1
B = np.ones(3)*2
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
print(np.multiply(A,B,out=A))

[-1.5 -1.5 -1.5]


In [91]:
# 36. Extract the integer part of a random array of positive numbers using 4 different methods

Z = np.random.uniform(0,10,10)

print(Z - Z%1)
print(Z // 1)
print(np.floor(Z))
print(Z.astype(int))
print(np.trunc(Z))

[0. 6. 3. 9. 2. 9. 5. 3. 4. 1.]
[0. 6. 3. 9. 2. 9. 5. 3. 4. 1.]
[0. 6. 3. 9. 2. 9. 5. 3. 4. 1.]
[0 6 3 9 2 9 5 3 4 1]
[0. 6. 3. 9. 2. 9. 5. 3. 4. 1.]


In [93]:
# 37. Create a 5x5 matrix with row values ranging from 0 to 4

a = np.zeros((5,5))
a += np.arange(5)
print(a)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [97]:
# 38. Consider a generator function that generates 10 integers and use it to build an array 

def generate():
    for x in range(10):
        yield x
a= np.fromiter(generate(),dtype=float,count=-1)
print(a)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [98]:
# 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded

a= np.linspace(0,1,11,endpoint=False)[1:]
print(a)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [99]:
# 40. Create a random vector of size 10 and sort it

a= np.random.random(10)
a.sort()
print(a)

[0.03865377 0.04241212 0.15526937 0.17716037 0.35526325 0.42917821
 0.67045118 0.82249558 0.91248574 0.93789467]


In [100]:
# 41. How to sum a small array faster than np.sum?

a= np.arange(10)
np.add.reduce(a)


45

In [101]:
# 42. Consider two random array A and B, check if they are equal


A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

equal = np.array_equal(A,B)
print(equal)

False


In [102]:
# 43. Make an array immutable (read-only)

a= np.zeros(10)
a.flags.writeable = False
a[0] = 1

ValueError: assignment destination is read-only

In [103]:
# 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates 

a= np.random.random((10,2))
X,Y = a[:,0], a[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[0.33149719 1.02954103 1.05953806 1.00405944 1.12254752 1.14455835
 0.64898889 0.55830388 0.91827191 0.94279149]
[0.35637554 0.64626507 1.02588806 0.97375873 0.49336768 0.91400275
 1.06978218 0.95763139 0.21259299 0.0929877 ]


In [104]:
# 45. Create random vector of size 10 and replace the maximum value by 0

a= np.random.random(10)
a[a.argmax()] = 0
print(a)

[0.36610546 0.19976135 0.68282699 0.53753374 0.40432274 0.
 0.09995824 0.14534481 0.62881024 0.68332327]


In [105]:
# 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area

a = np.zeros((5,5), [('x',float),('y',float)])
a['x'], a['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(a)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


In [106]:
# 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.163637117973


In [107]:
# 48. Print the minimum and maximum representable value for each numpy scalar type

for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


In [110]:
#49. How to print all the values of an array?  

 
np.set_printoptions(threshold=float("inf"))
a = np.zeros((40,40))
print(a)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [111]:
# 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

 
a = np.arange(100)
b= np.random.uniform(0,100)
index = (np.abs(a-b)).argmin()
print(a[index])

68


In [3]:
# 51. Create a structured array representing a position (x,y) and a color (r,g,b)

a= np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(a)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


<ipython-input-3-dc1ff3d69616>:3: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  a= np.zeros(10, [ ('position', [ ('x', float, 1),


In [6]:
# 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances  

a=np.random.random((100,2))
X,Y = np.atleast_2d(a[:,0], a[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

[[0.         0.5320845  0.2836045  ... 0.16817059 0.3164571  0.47840282]
 [0.5320845  0.         0.48532244 ... 0.69326794 0.24456167 0.07494442]
 [0.2836045  0.48532244 0.         ... 0.34476795 0.39078262 0.46932248]
 ...
 [0.16817059 0.69326794 0.34476795 ... 0.         0.48449457 0.64335411]
 [0.3164571  0.24456167 0.39078262 ... 0.48449457 0.         0.17616537]
 [0.47840282 0.07494442 0.46932248 ... 0.64335411 0.17616537 0.        ]]


In [7]:
# 53. How to convert a float (32 bits) array into an integer (32 bits) in place?
 
a=(np.random.rand(10)*100).astype(np.float32)
x=a.view(np.int32)
x[:]=a
print(x)

[90 89 12 38 75 49 94 87 37 17]


In [9]:
# 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

a= np.arange(4).reshape(2,2)
for index, value in np.ndenumerate(a):
    print(index, value)
for index in np.ndindex(a.shape):
    print(index, a[index])

(0, 0) 0
(0, 1) 1
(1, 0) 2
(1, 1) 3
(0, 0) 0
(0, 1) 1
(1, 0) 2
(1, 1) 3


In [10]:
# 56. Generate a generic 2D Gaussian-like array (★★☆)

X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

In [11]:
# 57. How to randomly place p elements in a 2D array? 

n = 8
p = 4
a= np.zeros((n,n))
np.put(a, np.random.choice(range(n*n), p, replace=False),1)
print(a)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]]


In [12]:
# 58. Subtract the mean of each row of a matrix  
 
X = np.random.rand(5, 10)
Y = X - X.mean(axis=1, keepdims=True)
Y = X - X.mean(axis=1).reshape(-1, 1)

print(Y)

[[-0.03024434 -0.21478389 -0.49022102  0.31904368 -0.47891209 -0.01428713
   0.29673085 -0.02577784  0.37149724  0.26695453]
 [-0.26676631  0.29293224  0.22163718  0.00733888 -0.25316331  0.28294533
  -0.63742048 -0.17334849  0.26372098  0.26212399]
 [-0.02742052 -0.04738617  0.28988133 -0.01366762 -0.04842681 -0.46696055
   0.12806731 -0.02739879 -0.04861135  0.26192316]
 [ 0.14199971  0.32943289 -0.14906674 -0.33505371 -0.01798963 -0.3650903
   0.00205862  0.46661955 -0.16669145  0.09378106]
 [ 0.09231009  0.14776033 -0.04617654  0.34240465 -0.28600548 -0.40883262
   0.15425704  0.33224931  0.04087563 -0.36884241]]


In [13]:
# 59. How to sort an array by the nth column? 
 
a= np.random.randint(0,10,(3,3))
print(a)
print(a[a[:,1].argsort()])

[[1 0 6]
 [9 1 4]
 [1 9 6]]
[[1 0 6]
 [9 1 4]
 [1 9 6]]


In [14]:
# 60. How to tell if a given 2D array has null columns?  

a= np.random.randint(0,3,(3,10))
print((~a.any(axis=0)).any())

True


In [15]:
# 61. Find the nearest value from a given value in an array
 
a= np.random.uniform(0,1,10)
b= 0.5
m = a.flat[np.abs(a-b).argmin()]
print(m)

0.5067952451707273


In [16]:
# 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator?  

A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [17]:
# 63. Create an array class that has a name attribute 

class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


In [19]:
# 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 
 

Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

[2. 3. 3. 4. 4. 2. 4. 3. 2. 3.]


In [20]:
# 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)?  

X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


In [21]:
# 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors 
 
w, h = 256, 256
I = np.random.randint(0, 4, (h, w, 3)).astype(np.ubyte)
colors = np.unique(I.reshape(-1, 3), axis=0)
n = len(colors)
print(n)

64


In [22]:
# 67. Considering a four dimensions array, how to get sum over the last two axis at once?  
 
A = np.random.randint(0,10,(3,4,3,4))
sum = A.sum(axis=(-2,-1))
print(sum)

[[56 42 68 57]
 [67 30 61 54]
 [57 75 63 44]]


In [23]:
# 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices?  
 
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)


[0.46771575 0.47429937 0.65245744 0.61489444 0.22321951 0.48851603
 0.45173442 0.64562811 0.56916176 0.50659739]


In [24]:
# 69. How to get the diagonal of a dot product

A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))
np.diag(np.dot(A, B))

array([1.33614467, 1.58363581, 1.16760427, 1.254919  , 0.83816948])

In [25]:
# 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value?  
 
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


In [26]:
# 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? 

A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


In [27]:
# 72. How to swap two rows of an array?  

A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [28]:
# 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles 

faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 0, 27) ( 0, 51) ( 1, 40) ( 1, 84) (10, 24) (10, 39) (10, 48) (10, 61)
 (16, 61) (16, 78) (24, 61) (25, 38) (25, 92) (26, 42) (26, 43) (27, 51)
 (29, 33) (29, 52) (33, 52) (34, 92) (34, 98) (38, 92) (39, 48) (40, 84)
 (42, 43) (61, 78) (76, 93) (76, 96) (92, 98) (93, 96)]


In [29]:
# 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C?  
 
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


In [30]:
# 75. How to compute averages using a sliding window over an array?  

def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


In [31]:
# 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) 
 
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.strides[0], a.strides[0])
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


In [32]:
# 77. How to negate a boolean, or to change the sign of a float inplace?  

Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)

Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)

array([-0.22560839,  0.34695795, -0.59618456, -0.41408098, -0.96302102,
       -0.57736208, -0.71598819, -0.89692123,  0.15225192,  0.62893052,
        0.06646091,  0.6947541 , -0.89695529, -0.08113885,  0.14304967,
       -0.03398084,  0.37623778, -0.38132602, -0.483816  , -0.72846517,
        0.93499959,  0.50097747, -0.44632226, -0.17428399,  0.37678538,
        0.45435274,  0.53973486,  0.06117444,  0.48555999,  0.45423686,
        0.00970459,  0.67853435,  0.10185394,  0.28680033, -0.58344709,
        0.85128152,  0.22787786, -0.45393075,  0.08406947,  0.20893217,
        0.6716287 ,  0.48771426,  0.81339811,  0.83840219, -0.4544283 ,
        0.31270337, -0.66452236,  0.76916359, -0.74879781,  0.85067406,
        0.05762931,  0.80845251,  0.08879153,  0.62916498,  0.82428915,
        0.53342359, -0.39565189,  0.17964132, -0.42564954, -0.18566197,
        0.85261303,  0.36338615,  0.65529991,  0.5246897 , -0.71636916,
        0.71011908, -0.30740978,  0.172554  ,  0.32845115, -0.99

In [33]:
# 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])?  
 
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[1.86461852 8.65806817 1.50472159 5.84378285 8.65677619 4.43409546
 3.00270912 4.68723146 1.18843331 5.76196687]


In [34]:
# 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])?  
 
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[ 3.46556104  6.29934799  2.16598045  7.64235321  1.76400765  6.02936588
   0.28345335  0.86637462  2.00592455  0.62537107]
 [ 5.5334703   2.68723889 11.48557375 16.1901128   6.50406442 15.66266705
   1.91877542 10.50120997  1.39683007  9.00000664]
 [ 7.35059532  5.89835681  1.6528113   5.44007989  1.65966516  2.74667692
   0.70562308  2.73545789  1.51472525  3.88916217]
 [ 0.44219925 11.96113268  5.45821242  5.86635835  3.34018723  6.98107556
   6.48155026  2.9933678   7.757979    0.26581526]
 [ 9.13085642  2.49407542  3.06654532  6.87529741  4.80219082  2.6817992
   4.34557084  3.46977754  1.93060728  3.91995441]
 [ 4.74761503  4.09467657  1.12210622  8.48851264  3.78249081  5.87228723
   2.0935257   0.26731168  0.2283317   0.75985249]
 [11.3752989   5.68346541  5.62982154  3.00644257  1.35293574  0.74364404
   1.53184712  6.52382057  1.20636493  7.36148893]
 [ 6.66651937  5.96751501  0.26557911 14.88761708 13.50260659  8.65951605
  12.34261329  1.29440829 10.33420482  2.11458679]
 

In [35]:
# 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary)  
 
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

[[9 5 1 9 0 4 4 9 5 5]
 [5 0 4 5 4 8 7 1 5 7]
 [4 0 8 5 9 7 3 6 9 2]
 [3 5 2 5 7 6 7 3 3 8]
 [5 5 6 9 3 3 5 8 7 1]
 [3 3 9 9 8 0 2 7 2 0]
 [3 7 0 0 7 8 4 4 0 9]
 [6 9 0 1 8 5 1 5 5 8]
 [6 1 8 6 2 6 1 6 7 8]
 [6 3 7 6 2 6 1 0 6 9]]
[[0 0 0 0 0]
 [0 9 5 1 9]
 [0 5 0 4 5]
 [0 4 0 8 5]
 [0 3 5 2 5]]


<ipython-input-35-a47bfd4232b7>:25: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  R[r] = Z[z]


In [37]:
# 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]?  
 
a= np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(a,(11,4),(4,4))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


In [39]:
# 82. Compute a matrix rank 

Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z)
rank = np.sum(S > 1e-10)
print(rank)

10


In [40]:
# 83. How to find the most frequent value in an array?
 
Z = np.random.randint(0,10,50)
print(np.bincount(Z).argmax())

7


In [41]:
# 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix 

Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

[[[[2 3 3]
   [1 2 0]
   [2 3 0]]

  [[3 3 2]
   [2 0 0]
   [3 0 0]]

  [[3 2 1]
   [0 0 2]
   [0 0 4]]

  [[2 1 1]
   [0 2 1]
   [0 4 2]]

  [[1 1 1]
   [2 1 3]
   [4 2 3]]

  [[1 1 3]
   [1 3 0]
   [2 3 3]]

  [[1 3 0]
   [3 0 0]
   [3 3 1]]

  [[3 0 4]
   [0 0 2]
   [3 1 1]]]


 [[[1 2 0]
   [2 3 0]
   [1 1 3]]

  [[2 0 0]
   [3 0 0]
   [1 3 0]]

  [[0 0 2]
   [0 0 4]
   [3 0 2]]

  [[0 2 1]
   [0 4 2]
   [0 2 2]]

  [[2 1 3]
   [4 2 3]
   [2 2 1]]

  [[1 3 0]
   [2 3 3]
   [2 1 1]]

  [[3 0 0]
   [3 3 1]
   [1 1 1]]

  [[0 0 2]
   [3 1 1]
   [1 1 4]]]


 [[[2 3 0]
   [1 1 3]
   [0 0 4]]

  [[3 0 0]
   [1 3 0]
   [0 4 2]]

  [[0 0 4]
   [3 0 2]
   [4 2 2]]

  [[0 4 2]
   [0 2 2]
   [2 2 3]]

  [[4 2 3]
   [2 2 1]
   [2 3 4]]

  [[2 3 3]
   [2 1 1]
   [3 4 0]]

  [[3 3 1]
   [1 1 1]
   [4 0 2]]

  [[3 1 1]
   [1 1 4]
   [0 2 2]]]


 [[[1 1 3]
   [0 0 4]
   [0 3 4]]

  [[1 3 0]
   [0 4 2]
   [3 4 3]]

  [[3 0 2]
   [4 2 2]
   [4 3 1]]

  [[0 2 2]
   [2 2 3]
   [3 1 2]]

  [[2 2 1]
   

In [42]:
# 85. Create a 2D array subclass such that Z[i,j] == Z[j,i]  

class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 4  9 13  6  2]
 [ 9  3 14  4 11]
 [13 14  5 42  8]
 [ 6  4 42  2  5]
 [ 2 11  8  5  5]]


In [43]:
# 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1))  
 
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


In [44]:
# 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)?  

Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


In [45]:
# 88. How to implement the Game of Life using numpy arrays?  

def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 1 1 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [46]:
# 89. How to get the n largest values of an array  

Z = np.arange(10000)
np.random.shuffle(Z)
n = 5
print (Z[np.argsort(Z)[-n:]])

[9995 9996 9997 9998 9999]


In [47]:
# 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) 
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


In [48]:
# 91. How to create a record array from a regular array? 

Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


In [50]:
# 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods  

x = np.random.rand(int(5e7))

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

2.56 s ± 172 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
547 ms ± 39 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
302 ms ± 39.2 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [51]:
# 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B?  
 
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[1]


In [53]:
# 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) 
Z = np.random.randint(0,5,(10,3))
print(Z)

[[1 2 4]
 [1 4 1]
 [0 1 3]
 [2 3 4]
 [1 3 3]
 [0 0 4]
 [2 2 2]
 [3 4 2]
 [2 4 2]
 [0 2 0]]


In [57]:
# 95. Convert a vector of ints into a matrix binary representation 
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


In [58]:
# 96. Given a two dimensional array, how to extract unique rows?
uZ = np.unique(Z, axis=0)
print(uZ)

[[0 0 4]
 [0 1 3]
 [0 2 0]
 [1 2 4]
 [1 3 3]
 [1 4 1]
 [2 2 2]
 [2 3 4]
 [2 4 2]
 [3 4 2]]


In [59]:
# 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function  

A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)       # np.sum(A)
np.einsum('i,i->i', A, B) # A * B
np.einsum('i,i', A, B)    # np.inner(A, B)
np.einsum('i,j->ij', A, B)    # np.outer(A, B)

array([[0.59340679, 0.70456525, 0.07527358, 0.22039472, 0.48419394,
        0.60473325, 0.11089974, 0.61885232, 0.22736217, 0.12245101],
       [0.05970075, 0.07088404, 0.00757303, 0.0221732 , 0.04871319,
        0.06084027, 0.01115727, 0.06226074, 0.02287418, 0.0123194 ],
       [0.52079642, 0.61835331, 0.06606296, 0.1934268 , 0.42494705,
        0.53073695, 0.09732984, 0.54312838, 0.1995417 , 0.10746767],
       [0.45835479, 0.54421496, 0.05814225, 0.17023562, 0.37399742,
        0.46710348, 0.08566034, 0.47800923, 0.17561737, 0.09458268],
       [0.58052068, 0.68926527, 0.07363897, 0.21560874, 0.47367943,
        0.59160118, 0.1084915 , 0.60541365, 0.22242489, 0.11979193],
       [0.2721003 , 0.32307081, 0.03451589, 0.10105962, 0.22202192,
        0.27729392, 0.05085188, 0.28376807, 0.10425447, 0.05614859],
       [0.53382641, 0.63382411, 0.06771581, 0.19826622, 0.43557896,
        0.54401565, 0.09976497, 0.5567171 , 0.20453411, 0.11015644],
       [0.08633934, 0.10251265, 0.0109521

In [64]:
# 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples  

phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 # segment lengths
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                # integrate path
r_int = np.linspace(0, r.max(), 200) # regular spaced path
x_int = np.interp(r_int, r, x)       # integrate path
y_int = np.interp(r_int, r, y)
print(r_int ,x_int, y_int)

[  0.           2.48788858   4.97577716   7.46366574   9.95155432
  12.43944289  14.92733147  17.41522005  19.90310863  22.39099721
  24.87888579  27.36677437  29.85466295  32.34255152  34.8304401
  37.31832868  39.80621726  42.29410584  44.78199442  47.269883
  49.75777158  52.24566016  54.73354873  57.22143731  59.70932589
  62.19721447  64.68510305  67.17299163  69.66088021  72.14876879
  74.63665736  77.12454594  79.61243452  82.1003231   84.58821168
  87.07610026  89.56398884  92.05187742  94.539766    97.02765457
  99.51554315 102.00343173 104.49132031 106.97920889 109.46709747
 111.95498605 114.44287463 116.9307632  119.41865178 121.90654036
 124.39442894 126.88231752 129.3702061  131.85809468 134.34598326
 136.83387184 139.32176041 141.80964899 144.29753757 146.78542615
 149.27331473 151.76120331 154.24909189 156.73698047 159.22486904
 161.71275762 164.2006462  166.68853478 169.17642336 171.66431194
 174.15220052 176.6400891  179.12797768 181.61586625 184.10375483
 186.59164341

In [61]:
# 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

 
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


In [62]:
# 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). 
 
X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.21846244  0.17621813]
